"use client";
import { useState } from "react";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [nav, setNav] = useState(false);
  const toggleNav = () => {
    setNav(!nav);
  };

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body data-nav={nav}>
        <button id="nav-toggle" onClick={toggleNav} type="button"></button>
        <main>{children}</main>
        <nav>
          <div id="nav-links">
            <Link href="/" className="nav-link">
              <h2 className="nav-link-label rubik-font">Home</h2>
              <Image
                width={500}
                height={500}
                alt=""
                className="nav-link-image"
                src="https://images.unsplash.com/photo-1513735492246-483525079686?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1932&q=80"
              />
            </Link>
            <Link href="/work" className="nav-link">
              <h2 className="nav-link-label rubik-font">Work</h2>
              <Image
                width={500}
                height={500}
                alt=""
                className="nav-link-image"
                src="https://images.unsplash.com/photo-1509718443690-d8e2fb3474b7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"
              />
            </Link>
            <Link href="/" className="nav-link">
              <h2 className="nav-link-label rubik-font">About</h2>
              <Image
                width={500}
                height={500}
                alt=""
                className="nav-link-image"
                src="https://images.unsplash.com/photo-1666005487638-61f45819c975?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80"
              />
            </Link>
            <Link href="/" className="nav-link">
              <h2 className="nav-link-label rubik-font">Contact</h2>
              <Image
                width={500}
                height={500}
                alt=""
                className="nav-link-image"
                src="https://images.unsplash.com/photo-1665910407771-bc84ad45676b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80"
              />
            </Link>
            <Link href="/" className="nav-link">
              <h2 className="nav-link-label rubik-font">Join Us</h2>
              <Image
                alt=""
                width={500}
                height={500}
                className="nav-link-image"
                src="https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80"
              />
            </Link>
          </div>
        </nav>
      </body>
    </html>
  );
}
